### ISSUE TITLE
complete-redux: reviews reverting to initial state on route change

### ISSUE THREAD

**Issue by danilo-89** [ProNextJS/state-management-tutorial#8]
**Description:**
In the "06-complete-redux" exercise, when you add a new review, it is correctly displayed.
However, if you navigate to a different product (error in console appears) and then return to the previous product with the newly added review, the new review is not visible.

**Steps to reproduce:**
1. go to any products page
2. add a new review
3. navigate to different product
4. navigate back to the previous product

**Video:**
(note: commented out "AverageRating" component)
[screen-capture (2).webm](https://github.com/ProNextJS/state-management-tutorial/assets/58806247/7d8f5c45-3ffd-4d81-9263-a1c4375d1ccc)

**Comment by jherr** [comment]
Add `revalidatePath` to the `addReviewAction` server action function:

```ts
  const addReviewAction = async (text: string, rating: number) => {
    "use server";
    const reviews = await addReview(+id, { text, rating });
    revalidatePath(`/products/${id}`);
    return reviews || [];
  };
```

**Comment by danilo-89** [comment]
@jherr , Thank you! 

Regarding console error that is still showing (only for the redux example) when adding review and then navigating to a different route, is that something that is possible to be fixed?
```
Warning: Cannot update a component (`AverageRating`) while rendering a different component (`AverageRating`).
To locate the bad setState() call inside `AverageRating`, follow the stack trace as described in
https://reactjs.org/link/setstate-in-render...
```

**Comment by jherr** [comment]
I'm not seeing that. You could migrate the initialization code to a
ReviewProvider that takes children and reviews then wrap the page in that
and remove the code from Reviews and AverageReviews.
